name: Build & deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 13.x
    
    - name: Install NPM packages
      run: npm ci
    
    - name: Build project
      run: npm run build
    
    - name: Copy DragDropInteractions
      shell: /bin/bash -e {0}
      run: |
        cp -vr "vendor/github.com/codrops/DragDropInteractions" "build/"

    - name: Install Node.js v16
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: Build lens-protocol-frontend
      shell: /bin/bash -e {0}
      run: |
        cd ./vendor/github.com/dabit3/lens-protocol-frontend
        yarn
        yarn build

    - name: Fix next.js absolute paths
      shell: /bin/bash -e {0}
      run: |
        cd ./vendor/github.com/dabit3/lens-protocol-frontend
        for file in `grep -l -r "/_next"`; do
          echo "update file: $file"
          sed -i "s+/_next/+_next/+g" $file
        done

    - name: Copy lens-protocol-frontend
      shell: /bin/bash -e {0}
      run: |
        cp -vr "./vendor/github.com/dabit3/lens-protocol-frontend/out" "build/lens-protocol-frontend"
   
    - name: Build polygon-ethereum-nextjs-marketplace
      shell: /bin/bash -e {0}
      run: |
        cd ./vendor/github.com/dabit3/polygon-ethereum-nextjs-marketplace
        npm prune
        yarn
        npx hardhat compile
        npm run build

    - name: Copy polygon-ethereum-nextjs-marketplace
      shell: /bin/bash -e {0}
      run: |
        cp -vr "./vendor/github.com/dabit3/polygon-ethereum-nextjs-marketplace/out" "build/marketplace"

    - name: Copy Ventus
      shell: /bin/bash -e {0}
      run: |
        mkdir -p ./build/Ventus
        cp -vr "./vendor/github.com/rlamana/Ventus/dist" "./build/Ventus/"
        cp -vr "./vendor/github.com/rlamana/Ventus/examples" "./build/Ventus/"

    - name: Upload production-ready build files
      uses: actions/upload-artifact@v2
      with:
        name: production-files
        path: ./build
  
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: production-files
        path: ./build

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
